name: 改善提案 / Improvement Suggestions
description: "「こうするとサイトがもっとよくなる」といった提案がある場合"
title: "Improvement : "
labels: [improvement]
body:
  - type: input
    id: input-1
    attributes:
      label: 改善詳細 / Details of Improvement
      description: できるだけ簡潔に / as concise as possible
    validations:
      required: true
  - type: textarea
    id: textarea-1
    attributes:
      label: スクリーンショット / Screenshot
      description: |
        バグであればdeveloper toolからコンソールも合わせて添付 / If it's a bug, attach a screenshot of the developer tool console
  - type: textarea
    id: textarea-2
    attributes:
      label: 期待する見せ方・挙動 / Expected Behavior
      description: 「何」が「どうなってほしいか」を記載 / Describe "what" and "how" you want it to happen.
    validations:
      required: true
  - type: dropdown
    id: dropdown-1
    attributes:
      label: OS
      options:
        - macOS
        - Windows
        - Linux
        - iOS
        - Android
      multiple: true
  - type: dropdown
    id: dropdown-2
    attributes:
      label: Browser
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
      multiple: true
